### PR TITLE
Query State Preview API implementation.

### LINKED ISSUE #685: state store query API: validate changes in the syntax of query JSON
Per work items below, the syntax of the state query JSON has been slightly changed, to make it more intuitive:
https://github.com/dapr/components-contrib/issues/1490
https://github.com/dapr/components-contrib/pull/1491
https://github.com/dapr/components-contrib/pull/1500
https://github.com/dapr/docs/pull/2195

Please validate this change in the SDK, and fix if necessary.

### LINKED ISSUE #702: Fix Service invocation path segments automatic encode of `/` into %2f
## Expected Behavior

Given a method name containing "/" in service invocation, properly split path segments and call dapr.

## Actual Behavior

Currently in PubSub IT,
https://github.com/dapr/java-sdk/blob/master/sdk-tests/src/test/java/io/dapr/it/pubsub/http/PubSubIT.java#L396-L400

The method being called is `messages/ttlTopic` which gets encoded as `messages%2fttlTopic` which was working prior to fix https://github.com/dapr/dapr/issues/4008. 

With the fix merged to Dapr, on Feb 8th, any build of Dapr after that fails the PubSub IT since it tries to invoke `http://...../messages%2fttltopic` instead of `http://..../messages/ttlTopic`. 

See https://github.com/dapr/java-sdk/runs/5533656018?check_suite_focus=true#step:20:6305

## Steps to Reproduce the Problem

Change Dapr Ref in build.yaml to any latest master ref from dapr/dapr and run the ITs. 

## Release Note

RELEASE NOTE: Fix service invocation path segments to avoid automatic encoding of `/` to `%2f`

### PR DESCRIPTION
**Pull request by mukundansundar**
Signed-off-by: Mukundan Sundararajan <msundar.ms@outlook.com>

# Description

changes made for query state API. 

The dependency updates are needed for Java SDK to successfully compile using Rosetta.

Have used MongoDb for querying stored state. 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #653 
closes #685 
closes #702 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

File: sdk/src/main/java/io/dapr/client/DaprClientHttp.java [hunk 1]
```diff
@@ -192,17 +196,21 @@
...
         throw new IllegalArgumentException("Method name cannot be null or empty.");
       }
-      byte[] serializedRequestBody = objectSerializer.serialize(request);
 
-      String[] pathSegments = new String[]{ DaprHttp.API_VERSION, "invoke", appId, "method", method };
 
+      String[] methodSegments = method.split("/");
+
+      List<String> pathSegments = new ArrayList<>(Arrays.asList(DaprHttp.API_VERSION, "invoke", appId, "method"));
+      pathSegments.addAll(Arrays.asList(methodSegments));
```
Comment (mukundansundar) [inline sdk/src/main/java/io/dapr/client/DaprClientHttp.java:204]: @artursouza This change is because of the change https://github.com/dapr/dapr/issues/4008

The PubsubIT was failing because the method name was `messages/ttlTopic` which was encoded as `messages%2FttlTopic` which worked before the previous change was made. 

Let me know if we can do it in a different way.

File: sdk/src/main/java/io/dapr/client/domain/QueryStateRequest.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+import java.util.Map;
+
+public class QueryStateRequest {
+
+  @JsonIgnore
+  private final String storeName;
+
+  private Query query;
+
+  private String queryString;
```
Comment (mukundansundar) [inline sdk/src/main/java/io/dapr/client/domain/QueryStateRequest.java:29]: @artursouza I have added both query and queryString as an option to either build query on the fly or read from file and use in the request. 

Let me know if that is ok.

File: pom.xml [hunk 3]
```diff
@@ -14,9 +14,9 @@
 
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <grpc.version>1.39.0</grpc.version>
-    <protobuf.version>3.13.0</protobuf.version>
-    <dapr.proto.baseurl>https://raw.githubusercontent.com/dapr/dapr/v1.6.0-rc.3/dapr/proto</dapr.proto.baseurl>
+    <grpc.version>1.42.1</grpc.version>
+    <protobuf.version>3.17.3</protobuf.version>
```
Comment (mukundansundar) [inline pom.xml:18]: @artursouza  Is there any concern in changing the protobuf version here ?

File: examples/pom.xml [hunk 4]
```diff
@@ -130,7 +130,7 @@
       <plugin>
         <groupId>com.github.os72</groupId>
         <artifactId>protoc-jar-maven-plugin</artifactId>
-        <version>3.10.1</version>
+        <version>3.11.4</version>
```
Comment (mukundansundar) [inline examples/pom.xml:133]: same here

File: examples/pom.xml [hunk 5]
```diff
@@ -61,7 +61,7 @@
     <dependency>
       <groupId>com.github.os72</groupId>
       <artifactId>protoc-jar-maven-plugin</artifactId>
-      <version>3.10.1</version>
+      <version>3.11.4</version>
```
Comment (mukundansundar) [inline examples/pom.xml:64]: same here ..

**Review by mukundansundar — COMMENTED** [review]
@artursouza Is there any concern on updating the protobuf and protoc versions to these values ?

File: daprdocs/content/en/java-sdk-docs/_index.md [hunk 6]
```diff
@@ -267,5 +269,65 @@ try (DaprPreviewClient client = (new DaprClientBuilder()).buildPreviewClient())
...
+
+try (DaprClient client = builder.build(); DaprPreviewClient previewClient = builder.buildPreviewClient()) {
+        String searchVal = args.length == 0 ? "searchValue" : args[0];
+        
+        // Create JSON data
+        MyData dataQueried = new MyData();
+        dataQueried.setPropertyA(searchVal);
+        dataQueried.setPropertyB("query");
+        MyData dataNotQueried = new MyData();
+        dataNotQueried.setPropertyA("no query");
```
Comment (artursouza) [inline daprdocs/content/en/java-sdk-docs/_index.md:295]: Please, use an example that resonates better with people: Movie, Product, Car - instead of arbitrary data.

File: examples/components/state/mongo.yaml [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+spec:
+  type: state.mongodb
+  version: v1
+  metadata:
+    - name: host
+      value: localhost:27017
+    - name: databaseName
+      value: local
+    - name: collectionName
+      value: testCollection
```
Comment (artursouza) [inline examples/components/state/mongo.yaml:14]: Please, use a better name, matching the data's domain.

File: pom.xml (hunk 3 above)
Comment (artursouza) [reply pom.xml:18]: No. LGTM.

File: sdk-tests/components/mongo-statestore.yml [hunk 8]
```diff
@@ -0,0 +1,14 @@
...
+spec:
+  type: state.mongodb
+  version: v1
+  metadata:
+    - name: host
+      value: localhost:27017
+    - name: databaseName
+      value: local
+    - name: collectionName
+      value: testCollection
```
Comment (artursouza) [inline sdk-tests/components/mongo-statestore.yml:14]: For tests, it is OK to have artificial names.

File: sdk/src/main/java/io/dapr/client/DaprPreviewClient.java [hunk 9]
```diff
@@ -103,4 +107,120 @@
...
+   * Query for states using a query string.
+   *
+   * @param storeName Name of the state store to query.
+   * @param query String value of the query.
+   * @param metadata Optional metadata passed to the state store.
+   * @param clazz The type needed as return for the call.
+   * @param <T> The Type of the return, use byte[] to skip serialization.
+   * @return A Mono of QueryStateResponse of type T.
+   */
+  <T> Mono<QueryStateResponse<T>> queryState(String storeName, String query,
```
Comment (artursouza) [inline sdk/src/main/java/io/dapr/client/DaprPreviewClient.java:121]: Awesome!

**Review by artursouza — CHANGES_REQUESTED** [review]
I will look into the expression building next. This is an awesome PR! Thanks.

File: sdk/src/main/java/io/dapr/client/domain/QueryStateRequest.java (hunk 2 above)
Comment (artursouza) [reply sdk/src/main/java/io/dapr/client/domain/QueryStateRequest.java:29]: LGTM. I really like the query class.

[the remark this answers is not in the document]
Comment (artursouza) [reply sdk/src/main/java/io/dapr/client/domain/QueryStateRequest.java:29]: LGTM

File: daprdocs/content/en/java-sdk-docs/_index.md (hunk 6 above)
Comment (mukundansundar) [reply daprdocs/content/en/java-sdk-docs/_index.md:295]: done

File: sdk-tests/components/mongo-statestore.yml (hunk 8 above)
Comment (mukundansundar) [reply sdk-tests/components/mongo-statestore.yml:14]: done

**Comment by mukundansundar** [comment]
Numeric value is not returned properly from MongoDB https://github.com/dapr/components-contrib/issues/1582 

Based on that using ID as string for now. Will later change to Integer once the above issue is fixed.

**Review by artursouza — APPROVED** [review]
